# Aqui devemos colocar os valores personaliz√°veis para o chart do Helm.
giropopsSenhas:
  name: "giropops-senhas-helm"
  image: "linuxtips/giropops-senhas:1.0"
  replicas: 2

redis:
  name: "redis-helm"
  image: "redis"