apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.giropopsSenhas.service.name }}
  labels:
    app: giropops-senhas
spec:
  type: {{ .Values.giropopsSenhas.service.type }}
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: {{ .Values.giropopsSenhas.service.port }}
      targetPort: {{ .Values.giropopsSenhas.service.targetPort }}
      name: tcp-app
