apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ .Values.redis.labels | toYamlPretty }} # utilizando função toYamlPretty para formatar corretamente o YAML
  name: {{ .Values.redis.name}}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{ .Values.redis.labels | toYamlPretty }}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: {{ .Values.redis.image }}
        name: redis
        ports:
          - containerPort: 6379
        resources:
          requests:
            memory: {{ .Values.redis.resources.requests.memory }}
            cpu: {{ .Values.redis.resources.requests.cpu }}
          limits:
            memory: {{ .Values.redis.resources.limits.memory }}
            cpu: {{ .Values.redis.resources.limits.cpu }}
